### ISSUE TITLE
what does the >: do? 

### ISSUE THREAD

**Issue by TheTechRobo** [lewiswatson55/Lost-Inspired-Countdown-Python-Program#2]
what does it do?

**Comment by lewiswatson55** [comment]
Which file/line are you referring to?

**Comment by lewiswatson55** [comment]
Which file/line are you referring too?

**Comment by TheTechRobo** [comment]
The one with _>

countdown-files/countdown.py

Thanks! Also check out my fork— it has plenty of new features :)

Sent from TtR's iPhone 4

Le 2 sept. 2019 à 11:52, "Lewis Watson" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Which file/line are you referring too?

**Comment by TheTechRobo** [comment]
Here is a more readable one: 

The one with _>

countdown-files/countdown.py

Thanks!

Also check out my fork — it has plenty of new features

**Comment by lewiswatson55** [comment]
Ah I see, "u_input = input("_> ")".

Well actually, I just checked google and found the swan computer actually uses >: and not _>... So I'll have to update that thanks!

All the line does is display whatever is between the quotation marks on screen before the user enters text. So for a password you could write 'password = input("Password: ")'.

For sure ill check out your fork! Feel free to make a pull request if you'd like.

**Comment by TheTechRobo** [comment]
ok thanks!

**Comment by TheTechRobo** [comment]
I did a PR. Closing the issue...
