### ISSUE TITLE
More accurate time

### ISSUE THREAD

**Issue by TheTechRobo** [lewiswatson55/Lost-Inspired-Countdown-Python-Program#6]
You may be interested in [`timeit` module](https://docs.python.org/3/library/timeit.html). It give more accurate results than subtracting `time.time`.

**Comment by lewiswatson55** [comment]
Thanks! Not working on this program at the moment but when I do I'll take a look!

**Comment by TheTechRobo** [comment]
:)

**Comment by TheTechRobo** [comment]
Oops! I think this should be in your Collatz repo.
